trac-ui/apps/app_run/urls.py
from django.urls import path

from .views import *

app_name = "app_run"

urlpatterns = [
    path("<int:instance_id>/runs/create/", create_run, name="create_run"),
    path("<int:instance_id>/runs/<int:run_id>/update/", update_run, name="update_run"),
    path("<int:instance_id>/runs/<int:run_id>/delete/", delete_run, name="delete_run"),
    path(
        "<int:instance_id>/runs/<int:run_id>/view/", view_run_result, name="view_result"
    ),
    path("<int:instance_id>/runs/<int:run_id>/logs/", view_run_logs, name="view_logs"),
]

trac-ui/apps/data_gateway/urls.py
from django.urls import path

from .data_gateway_views import *
from .views import *

app_name = "data_gateway"

urlpatterns = [
    path("<int:instance_id>/datasets/create/", create_dataset, name="create_dataset"),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/update/",
        update_dataset,
        name="update_dataset",
    ),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/delete/",
        delete_dataset,
        name="delete_dataset",
    ),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/manage/",
        dataset_input_view,
        name="view_input",
    ),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/save/",
        dataset_input_view_save,
        name="save_data",
    ),
    path(
        "datasets/<int:dataset_id>/spec.json", dataset_api_spec, name="dataset_api_spec"
    ),
    path(
        "datasets/<int:dataset_id>/swagger-ui",
        dataset_api_swagger_ui,
        name="dataset_swagger_ui",
    ),
    path(
        "datasets/<int:dataset_id>/api/<str:resource_type>/",
        ResourceListCreateView.as_view(),
        name="resource_list_create",
    ),
    path(
        "datasets/<int:dataset_id>/api/<str:resource_type>/<int:resource_id>/",
        ResourceDetailView.as_view(),
        name="resource_retrieve_update_destroy",
    ),
]

trac-ui/apps/trac_app/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from .views import (
    AppDefinitionViewSet,
    AppInstanceListCreateAPIView,
    AppInstanceRetrieveUpdateDestroyAPIView,
    dashboard,
)

app_name = "trac_app"

router = SimpleRouter()
router.register(r"api/apps", AppDefinitionViewSet, basename="app")

urlpatterns = [
    path("instances/<int:instance_id>/dashboard/", dashboard, name="dashboard"),
    path(
        "api/apps/<int:app_def_id>/instances/",
        AppInstanceListCreateAPIView.as_view(),
        name="app_instance_list",
    ),
    path(
        "api/apps/<int:app_def_id>/instances/<int:app_inst_id>",
        AppInstanceRetrieveUpdateDestroyAPIView.as_view(),
        name="app_instance_detail",
    ),
]

urlpatterns += router.urls

trac-ui/trac_ui/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.trac_app.urls")),
    path("data_gateway/", include("apps.data_gateway.urls")),
    path("app_run/", include("apps.app_run.urls")),
]

trac-ui/apps/trac_app/models.py
from functools import cached_property, lru_cache

from django.db import models

from .docker_utils import DockerUtils


class AppDefinition(models.Model):

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    image_name = models.CharField(max_length=100)
    image_tag = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    @property
    def default_task(self):
        return self.tasks[0]

    @cached_property
    def spec(self):
        """
        Return the spec of the app
        """
        return DockerUtils.spec(self.image_name, self.image_tag)

    @cached_property
    def tasks(self):
        """
        Return the tasks of the app
        """
        return DockerUtils.tasks(self.image_name, self.image_tag)

    @lru_cache
    def task_spec(self, task_name=None):
        """
        Return the spec of a task
        If task_name is None, return the default task
        """
        task_name = task_name or self.default_task
        return DockerUtils.spec(self.image_name, self.image_tag, task_name)

    @lru_cache
    def input_schema(self, task_name=None):
        """
        Return the input schema of the app
        """
        if not task_name:
            task_name = self.default_task
        return DockerUtils.input_schema(
            self.image_name, self.image_tag, task_name=task_name
        )

    @lru_cache
    def output_schema(self, task_name=None):
        """
        Return the output schema of the app
        """

        if not task_name:
            task_name = self.default_task
        return DockerUtils.output_schema(
            self.image_name, self.image_tag, task_name=task_name
        )

    @lru_cache
    def parameter_schema(self, task_name=None):
        """
        Return the parameter schema of the app
        """
        if not task_name:
            task_name = self.default_task
        return DockerUtils.parameter_schema(
            self.image_name, self.image_tag, task_name=task_name
        )


class AppInstance(models.Model):

    app = models.ForeignKey(AppDefinition, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

trac-ui/apps/trac_app/views.py
from django.shortcuts import render
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.serializers import ModelSerializer, ValidationError
from rest_framework.viewsets import ModelViewSet

from .models import AppDefinition, AppInstance


class AppDefinitionSerializer(ModelSerializer):
    class Meta:
        model = AppDefinition
        fields = "__all__"


class AppInstanceSerializer(ModelSerializer):
    class Meta:
        model = AppInstance
        fields = [
            "id",
            "name",
            "description",
        ]


class AppDefinitionViewSet(ModelViewSet):
    queryset = AppDefinition.objects.all().order_by("pk")
    serializer_class = AppDefinitionSerializer


# /api/apps/<app_def_id>/instances
class AppInstanceListCreateAPIView(ListCreateAPIView):
    serializer_class = AppInstanceSerializer

    def get_queryset(self):
        app_def_id = self.kwargs["app_def_id"]
        return AppInstance.objects.filter(app__pk=app_def_id).all()

    def perform_create(self, serializer):
        app_def_id = self.kwargs["app_def_id"]
        app_def = AppDefinition.objects.get(id=app_def_id)
        serializer.save(app=app_def)


# /api/apps/<app_def_id>/instances/<app_inst_id>
class AppInstanceRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = AppInstanceSerializer
    queryset = AppInstance.objects.all()

    def get_object(self):
        app_def_id = self.kwargs["app_def_id"]
        app_inst_id = self.kwargs["app_inst_id"]
        return self.get_queryset().filter(app__pk=app_def_id, id=app_inst_id).first()


# /instances/<instance_id>/dashboard
def dashboard(request, instance_id):
    app = AppInstance.objects.get(id=instance_id)

    # all runs belong to this instance
    runs = app.runs.all()

    datasets = app.datasets.all()

    context = {
        "runs": runs,
        "datasets": datasets,
        "instance_id": instance_id,
    }

    return render(
        request,
        "trac_app/manage_instance.html",
        context,
    )

trac-ui/apps/trac_app/templates/trac_app/manage_instance.html
{% extends 'base.html' %}

{% block content %}
<!-- nav tabs -->
<div class="m-2">
<ul class="nav nav-pills" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="pills-data-tab" data-bs-toggle="pill" data-bs-target="#pills-dataset" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Dataset</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="pills-run-tab" data-bs-toggle="pill" data-bs-target="#pills-run" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Run</button>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-dataset" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
    {% include 'trac_app/manage_instance_datasets.html' %}
  </div>
  <div class="tab-pane fade" id="pills-run" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
    {% include 'trac_app/manage_instance_runs.html' %}
  </div>
</div>



</div>



{% endblock %}

trac-ui/apps/trac_app/templates/trac_app/manage_instance_datasets.html
<!-- The dashboard page for managing an instance -->
<div class="container">
    <!-- a button to register a new dataset, aligned to right -->
    <div class="row justify-content-end">
        <div class="col-md-2">
            <a href="{% url 'data_gateway:create_dataset' instance_id %}" class="btn btn-primary float-end">Create a
                dataset</a>
        </div>
    </div>

    <!-- a table to show all datasets -->
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Dataset Name</th>
                        <th scope="col">Dataset Description</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dataset in datasets %}
                    <tr>
                        <td>
                            <a href="{% url 'data_gateway:view_input' instance_id dataset.id %}">
                                {{ dataset.name }}
                            </a>
                        </td>
                        <td>{{ dataset.description }}</td>
                        <!-- A dropdown menu with more_event icon -->
                        <td>
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                                    id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="fas fa-ellipsis-v"></i>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li>
                                        <a class="dropdown-item"
                                            href="{% url 'data_gateway:update_dataset' instance_id dataset.id %}">Edit</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                            href="{% url 'data_gateway:dataset_swagger_ui' dataset.id %}">API Spec</a>
                                    </li>
                                    <li>
                                        <!-- A delete form -->
                                        <form action="{% url 'data_gateway:delete_dataset' instance_id dataset.id %}">
                                            {% csrf_token %}
                                            <a class="dropdown-item" type="submit">Delete</a>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

trac-ui/apps/trac_app/templates/trac_app/manage_instance_runs.html
<!-- The dashboard page for managing an instance -->


<div class="container">
    <!-- a button to create a new run, aligned to right -->
    <div class="row justify-content-end">
        <div class="col-md-2">
            <a href="{% url 'app_run:create_run' instance_id %}" class="btn btn-primary float-end">Create a run</a>
        </div>
    </div>

    <!-- a table to show all runs -->
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Run Name</th>
                        <th scope="col">Run Description</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for run in runs %}
                    <tr>
                        <td>
                            <a href="{% url 'app_run:view_result' instance_id run.id %}">
                                {{ run.name }}
                            </a>
                        </td>
                        <td>{{ run.description }}</td>
                        <td>
                            {{ run.status }}
                        </td>
                        <!-- A dropdown menu with more_event icon -->
                        <td>
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                                    id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    <i class="fas fa-ellipsis-v"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item"
                                        href="{% url 'app_run:update_run' instance_id run.id %}">Edit</a>
                                    <a href="{% url 'app_run:view_logs' instance_id run.id %}" class="dropdown-item">View logs</a>
                                    <form action="{% url 'app_run:delete_run' instance_id run.id %}">
                                        {% csrf_token %}
                                        <a type="submit" class="dropdown-item">Delete</a>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>