trac-ui/apps/data_gateway/urls.py
from django.urls import path

from .data_gateway_views import *
from .views import *

app_name = "data_gateway"

urlpatterns = [
    path("<int:instance_id>/datasets/create/", create_dataset, name="create_dataset"),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/update/",
        update_dataset,
        name="update_dataset",
    ),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/delete/",
        delete_dataset,
        name="delete_dataset",
    ),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/manage/",
        dataset_input_view,
        name="view_input",
    ),
    path(
        "<int:instance_id>/datasets/<int:dataset_id>/save/",
        dataset_input_view_save,
        name="save_data",
    ),
    path(
        "datasets/<int:dataset_id>/spec.json", dataset_api_spec, name="dataset_api_spec"
    ),
    path(
        "datasets/<int:dataset_id>/swagger-ui",
        dataset_api_swagger_ui,
        name="dataset_swagger_ui",
    ),
    path(
        "datasets/<int:dataset_id>/api/<str:resource_type>/",
        ResourceListCreateView.as_view(),
        name="resource_list_create",
    ),
    path(
        "datasets/<int:dataset_id>/api/<str:resource_type>/<int:resource_id>/",
        ResourceDetailView.as_view(),
        name="resource_retrieve_update_destroy",
    ),
]

trac-ui/apps/trac_app/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from .views import (
    AppDefinitionViewSet,
    AppInstanceListCreateAPIView,
    AppInstanceRetrieveUpdateDestroyAPIView,
    dashboard,
)

app_name = "trac_app"

router = SimpleRouter()
router.register(r"api/apps", AppDefinitionViewSet, basename="app")

urlpatterns = [
    path("instances/<int:instance_id>/dashboard/", dashboard, name="dashboard"),
    path(
        "api/apps/<int:app_def_id>/instances/",
        AppInstanceListCreateAPIView.as_view(),
        name="app_instance_list",
    ),
    path(
        "api/apps/<int:app_def_id>/instances/<int:app_inst_id>",
        AppInstanceRetrieveUpdateDestroyAPIView.as_view(),
        name="app_instance_detail",
    ),
]

urlpatterns += router.urls

trac-ui/trac_ui/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.trac_app.urls")),
    path("data_gateway/", include("apps.data_gateway.urls")),
    path("app_run/", include("apps.app_run.urls")),
]

trac-ui/apps/data_gateway/models.py
import hashlib
import json

from apps.trac_app.models import AppInstance
from django.db import models
from trac.schema.task import FileDef


# custom json decoder for the schema type
# schema takes the form {"input_schema": List[FileDef], "output_schema": List[FileDef]}
class FileDefListDecoder(json.JSONDecoder):
    def decode(self, s):
        d = super().decode(s)
        if isinstance(d, dict):
            for k, v in d.items():
                if isinstance(v, list):
                    d[k] = [FileDef(**x) for x in v]
        return d


# custom json encoder for the schema type
# schema takes the form {"input_schema": List[FileDef], "output_schema": List[FileDef]}
class FileDefListEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, FileDef):
            return o.dict()
        else:
            return super().default(o)


class DataSet(models.Model):
    """
    A dataset = a workbook in excel
    """

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    app = models.ForeignKey(
        AppInstance, on_delete=models.CASCADE, related_name="datasets"
    )

    schema = models.JSONField(
        blank=True, null=True, decoder=FileDefListDecoder, encoder=FileDefListEncoder
    )

    initialized = models.BooleanField(default=False)
    url = models.CharField(max_length=1000, blank=True, null=True)
    backend = models.CharField(
        max_length=100,
        choices=[
            ("excel", "Excel"),
            ("db", "Database"),
            ("gsheet", "Google Sheet"),
        ],
        default="db",
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # reoder the keys and values in the schema in alphabetical order recursively
        self.schema = self._sort_dict(self.schema)
        super().save(*args, **kwargs)

    def _sort_dict(self, d):
        if isinstance(d, dict):
            return {k: self._sort_dict(v) for k, v in sorted(d.items())}
        elif isinstance(d, list):
            return [self._sort_dict(x) for x in d]
        else:
            return d

    def schema_hash(self):
        """
        Hash value of the schema
        So that we can compare the schema of two datasets
        """
        return hashlib.sha256(str(self.schema).encode("utf-8")).hexdigest()


class Resource(models.Model):
    """
    A resource is a sheet in a workbook
    """

    dataset = models.ForeignKey(
        DataSet, on_delete=models.CASCADE, related_name="resources"
    )
    resource_type = models.CharField(max_length=100)
    value = models.JSONField(null=True, blank=True)

    def __str__(self):
        return self.name

trac-ui/apps/data_gateway/forms.py
from django import forms

from .models import DataSet


class DatasetForm(forms.ModelForm):
    class Meta:
        model = DataSet
        fields = ["name", "description", "backend"]

trac-ui/apps/data_gateway/views.py
import json
import uuid
from typing import List

from apps.trac_app.models import AppInstance
from django.db import transaction
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from trac.schema.task import FileDef

from .forms import DatasetForm
from .models import DataSet, Resource
from .schema_utils import generate_openapi_schema_for_dataset
from .services.gsheet import GoogleSheetsDataBackend


def create_dataset(request, instance_id):
    """
    Create a DataSet when request is POST
    """
    if request.method == "POST":
        form = DatasetForm(request.POST)
        if form.is_valid():
            dataset = form.save(commit=False)
            dataset.app = AppInstance.objects.get(id=instance_id)
            # set the schema field of the dataset
            app = dataset.app
            # get the app_definition of the app
            app_def = app.app
            # get the schema of the app_def
            schema = {
                "input_schema": app_def.input_schema(),
                "output_schema": app_def.output_schema(),
            }
            dataset.schema = schema

            # if the dataset backend is gsheet, call the gsheet api to create a new spreadsheet
            uniq_identifier = str(uuid.uuid4())[:8]
            spreadsheet_name = dataset.name + "_" + uniq_identifier
            if dataset.backend == "gsheet":
                sheet_url = GoogleSheetsDataBackend.init_spreadsheet(
                    dataset.schema["input_schema"], spreadsheet_name=spreadsheet_name
                )

                dataset.url = sheet_url

            dataset.initialized = True

            dataset.save()
            return redirect("trac_app:dashboard", instance_id=instance_id)
    else:
        form = DatasetForm()
    return render(
        request,
        "data_gateway/create_dataset.html",
        {"form": form, "instance_id": instance_id},
    )


def update_dataset(request, instance_id, dataset_id):
    """
    Update a DataSet when request is PUT
    """
    dataset = DataSet.objects.get(id=dataset_id)
    if request.method == "POST":
        form = DatasetForm(request.POST, instance=dataset)
        if form.is_valid():

            new_dataset = form.save(commit=False)
            new_dataset.app = dataset.app
            # set the schema field of the dataset
            app = new_dataset.app
            # get the app_definition of the app
            app_def = app.app
            # get the schema of the app_def
            schema = {
                "input_schema": app_def.input_schema(),
                "output_schema": app_def.output_schema(),
            }
            new_dataset.schema = schema
            new_dataset.save()
            return redirect("trac_app:dashboard", instance_id=instance_id)
    else:
        form = DatasetForm(instance=dataset)
    return render(
        request,
        "data_gateway/create_dataset.html",
        {"form": form, "instance_id": instance_id},
    )


def delete_dataset(request, instance_id, dataset_id):
    """
    Delete a DataSet when request is DELETE
    """
    if request.method == "POST":
        dataset = DataSet.objects.get(id=dataset_id)
        dataset.delete()
        return redirect("trac_app:dashboard", instance_id=instance_id)


def dataset_input_view(request, instance_id, dataset_id):
    """
    Show a dataset input view when request is GET
    Render all the resources in the spreadsheet form
    """
    dataset = DataSet.objects.get(id=dataset_id)

    if dataset.backend == "gsheet":
        # redirect to the gsheet view in a new tab
        return redirect(dataset.url)

    input_schema: List[FileDef] = dataset.schema["input_schema"]

    workbook_data = []
    for resource_schema in input_schema:
        # resource_schema is a jsonschema that defines an object
        resource_name = resource_schema.name
        # header names
        field_names = list(resource_schema.file_schema["properties"].keys())
        # data
        resources = Resource.objects.filter(
            dataset=dataset, resource_type=resource_name
        ).all()

        celldata = []
        # header
        for idx, name in enumerate(field_names):
            celldata.append({"r": 0, "c": idx, "v": name})

        # data
        for idx, resource in enumerate(resources):
            for jdx, name in enumerate(field_names):
                celldata.append({"r": idx + 1, "c": jdx, "v": resource.value.get(name)})

        workbook_data.append({"name": resource_name, "celldata": celldata})

    context = {
        "workbook_data": json.dumps(workbook_data),
        "instance_id": instance_id,
        "dataset_id": dataset_id,
    }

    return render(request, "data_gateway/view_data.html", context=context)


def dataset_input_view_save(request, instance_id, dataset_id):
    """
    Update or create a resource when request is PUT or POST
    """
    # decide if the request is ajax
    if request.headers.get("X-Requested-With") == "XMLHttpRequest":

        if request.method == "POST":
            # get data schema
            dataset = DataSet.objects.get(id=dataset_id)
            input_schema = dataset.schema["input_schema"]

            payload = json.loads(request.POST["data"])
            # TODO: validate the payload
            resources_to_add = []
            for sheet in payload:
                sheet_name = sheet["name"]
                # get the schema with title == sheet_name
                resource_schema = next(
                    (x for x in input_schema if x.name == sheet_name), None
                )
                field_names = list(resource_schema.file_schema["properties"].keys())
                cell_data = sheet["data"]
                # drop the first row
                cell_data = cell_data[1:]

                for idx, row in enumerate(cell_data):
                    resource_value = {}
                    for jidx, cell in enumerate(row):
                        if not cell:
                            break
                        field_name = field_names[jidx]
                        value = cell["v"]
                        resource_value[field_name] = value

                    # construct a resource
                    resource = Resource(
                        dataset=dataset, resource_type=sheet_name, value=resource_value
                    )

                    resources_to_add.append(resource)

            # start a transaction
            with transaction.atomic():
                # TODO: this is very inefficient
                # delete all the resources
                Resource.objects.filter(dataset=dataset).delete()
                # add all the resources
                Resource.objects.bulk_create(resources_to_add)
            # get the number of resources impacted
            num_resources = len(resources_to_add)

            return HttpResponse("OK. {} resources added".format(num_resources))

    else:
        return HttpResponse(status=400, reason="Bad Request")


def dataset_api_spec(request, dataset_id):
    """
    Generate a swagger spec for a dataset
    """
    dataset = DataSet.objects.get(id=dataset_id)
    oas_schema = generate_openapi_schema_for_dataset(dataset)

    # return a json response wrapping the oas_schema
    return JsonResponse(oas_schema)


def dataset_api_swagger_ui(request, dataset_id):
    """
    Return a swagger UI that renders the spec
    """
    return render(
        request,
        "data_gateway/swagger_ui.html",
        {
            "schema_url": reverse("data_gateway:dataset_api_spec", args=[dataset_id]),
        },
    )

trac-ui/apps/data_gateway/templates/data_gateway/create_dataset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'trac_app:dashboard' instance_id %}">Data</a></li>
    <li class="breadcrumb-item active">
      Create
    </li>
  </ol>
</nav>


<div class="row justify-content-center">
  <div class="col-md-8">
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}

      <div class="row justify-content-end">
        <div class="col-md-3">
          <div class="float-end">

            <a href="{% url 'trac_app:dashboard' instance_id %}" class="btn">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>

        </div>
      </div>
    </form>
  </div>
</div>





{% endblock %}

trac-ui/apps/data_gateway/templates/data_gateway/swagger_ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{{ schema_url }}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        // requestInterceptor: (request) => {
        //   request.headers['X-CSRFToken'] = "{{ csrf_token }}"
        //   return request;
        // }
      })
    </script>
  </body>
</html>

trac-ui/apps/data_gateway/templates/data_gateway/view_data.html
{% extends 'base.html' %}


{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'trac_app:dashboard' instance_id %}">Data</a></li>
        <li class="breadcrumb-item active"><a href="#">Edit</a></li>
    </ol>
</nav>


<div class="row justify-content-end">
    <div class="col-md-2 m-2">
        <div class="float-end">

            <a href="{% url 'trac_app:dashboard' instance_id %}" class="btn">
                Cancel
            </a>
            <button id="save_data" class="btn btn-primary">
                Save Dataset
            </button>
        </div>

    </div>
</div>

<div id="luckysheet" style="margin:0px;padding:0px;width:100%;height:100%;left: 0px;top: 0px;"></div>

{% endblock %}


{% block script %}

<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet/dist/plugins/css/pluginsCss.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet/dist/plugins/plugins.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet/dist/css/luckysheet.css' />
<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/luckysheet/dist/assets/iconfont/iconfont.css' />
<script src="https://cdn.jsdelivr.net/npm/luckysheet/dist/plugins/js/plugin.js"></script>
<script src="https://cdn.jsdelivr.net/npm/luckysheet/dist/luckysheet.umd.js"></script>

<script>
    $(function () {
        //配置项
        var options = {
            container: 'luckysheet', //luckysheet为容器id
            showinfobar: false,
            data: JSON.parse('{{ workbook_data | safe }}')
        }
        luckysheet.create(options);

    })

    $(function () {
        // bind a click event to the button
        $('#save_data').click(function () {
            var data = luckysheet.getluckysheetfile();
            // for each object in data, just keep the name and data fields
            data = data.map(function (obj) {
                sheetData = obj.data;
                // filter out the empty rows
                sheetData = sheetData.filter(function (row) {
                    return row.some(function (cell) {
                        return cell != null;
                    });
                });
                return {
                    name: obj.name,
                    data: sheetData
                }
            })

            console.log(data);

            // send the data to the server
            $.ajax({
                url: '{% url "data_gateway:save_data" instance_id dataset_id %}',
                type: 'POST',
                data: {
                    'data': JSON.stringify(data),
                },
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'X-Requested-With': 'XMLHttpRequest'
                },
                success: function (response) {
                    console.log(response);
                    // show a success message
                    alert('Data saved successfully');

                },
                error: function (error) {
                    console.log(error);
                }
            });

        });
    })
</script>


{% endblock %}